### ISSUE TITLE
能不能可选转换为flac格式的呢

### ISSUE THREAD

**Issue by SPOREIII** [charlotte-xiao/NCM2MP3#2]
其他几个项目的转换玩听起来一耳朵的差

**Comment by yhmpc** [comment]
这个好像取决于你下载的源文件。下载的是FLAC格式，转换后就是FLAC格式，如图：
![demo](https://vip1.loli.io/2022/01/22/fZJioF1ukDebpLa.png)

**Comment by SPOREIII** [comment]
已收到您的邮件，祝您生活愉快！                                         唐为昊                                    15869106706

**Comment by charlotte-xiao** [comment]
是这样的，转换后是网易云源文件的格式

**Comment by SPOREIII** [comment]
已收到您的邮件，祝您生活愉快！                                         唐为昊                                    15869106706
